name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:         # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # Generate Snake animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AkshatMore15
          outputs: dist/snake.svg

      # Push to output branch
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
